[package]
name = "l2e-app"
version = "0.1.0"
edition = "2021"

[dependencies]
sails-rs = "0.4.0"
gstd = "1.5.0"
scale-info = { version = "*", default-features = false }
parity-scale-codec = { version = "*", default-features = false }

